[build]
builder            = "DOCKERFILE"
dockerfilePath     = "Dockerfile"

[deploy]
# Porta exposta pelo Puma / Thruster
# Railway injeta $PORT automaticamente
startCommand       = "bundle exec rails server -b 0.0.0.0"
healthcheckPath    = "/up"
healthcheckTimeout = 300

restartPolicyType       = "ON_FAILURE"
restartPolicyMaxRetries = 5
